name: Build IPI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Set env vars
      run: |
        echo "llvm_ver=12.0" >> $GITHUB_ENV
        echo "OO_PS4_TOOLCHAIN=${GITHUB_WORKSPACE}/OpenOrbis/PS4Toolchain" >> $GITHUB_ENV

    - name: Cache OpenOrbis Toolchain
      id: cache-oosdk
      uses: actions/cache@v3
      with:
        path: ${{ env.OO_PS4_TOOLCHAIN }}
        key: ${{ runner.os }}-oosdk-llvm-${{ env.llvm_ver }}

    # temporary release until 0.53 is released
    - name: Download OpenOrbis Toolchain
      if: steps.cache-oosdk.outputs.cache-hit != 'true'
      run: curl -sL https://github.com/illusion0001/OpenOrbis-PS4-Toolchain/releases/download/0.0.1.461/toolchain.tar.gz | tar xz -C ./

    - name: Cache LLVM and Clang
      id: cache-llvm
      uses: actions/cache@v3
      with:
        path: ./llvm
        key: llvm-${{ env.llvm_ver }}

    - name: Install LLVM and Clang
      uses: KyleMayes/install-llvm-action@v1
      with:
        version: ${{ env.llvm_ver }}
        cached: ${{ steps.cache-llvm.outputs.cache-hit }}

    - name: Build app
      run: make && ls

    - name: Push package artifact
      uses: actions/upload-artifact@v3
      with:
        name: IPI
        path: IV0000-KPBR01111_00-AAAAAAAAAAAAAAAA.pkg
      # if-no-files-found: error
